### ISSUE TITLE
Trying to run on IOS

### ISSUE THREAD

**Issue by boehm-e** [NickHardeman/ofxFBX#13]
First, I d'like  to thank you for your great addon!
It runs very well on Desktop (mac) but I can't get it working on IOS.
The problem seems related with glew : 
`Use of undeclared identifier 'GL_FILL'`
when calling `glPolygonMode` (which is not defined as well)
So it seems to be an include problem, but i can't find out the solution.
Does anyone has knows a solution?

Thanks

**Comment by NickHardeman** [comment]
Thank you. What version of OF are you using? I have not upgraded to the add-on to be compatible with 0.10 yet. So that might be the issue.

**Comment by boehm-e** [comment]
Hi, thanks for your reply.
I  am running OF v0.9.8 :/

**Comment by NickHardeman** [comment]
I forgot that there is no static FBX lib in this add-on for iOS. Currently it only supports 32 and 64 bit versions for osx and visual studio. If you were to build it for iOS, it should work though...but I have not tested.

**Comment by NickHardeman** [comment]
The iOS libs have been updated and are working properly with the current 0.10.1 version of OF on the device. 
Thank you. :)
