### ISSUE TITLE
texture not drawn on iOS.

### ISSUE THREAD

**Issue by sadmb** [NickHardeman/ofxFBX#15]
I have succeeded to make it work on iOS.
But texture is not shown on FBX while it shows on MacOS.

Also it is shown on "FBX Review" app which is official viewer app for FBX on iOS.

I am using iOS 12.1.

![img_0003](https://user-images.githubusercontent.com/548587/53413183-b01aa480-3a0e-11e9-9eba-02e7467043f9.PNG)
no texture on the model

![img_0005](https://user-images.githubusercontent.com/548587/53413213-c45ea180-3a0e-11e9-9935-e8a16dcf4743.PNG)
texture on the model with FBX Review.

**Comment by NickHardeman** [comment]
Sorry for the delayed response. The included Anim-Transitions and Bone Control examples shows how to load a texture for fbx. You probably need to call ofDisableArbTex before calling load on the fbx.
