### ISSUE TITLE
Release and Debug

### ISSUE THREAD

**Issue by BrendanKatapult** [NickHardeman/ofxFBX#16]
Thanks for the Library! 
I managed to get this running in release and debug by linking the correct libs from Autodesk which can be downloaded here: [https://www.autodesk.com/developer-network/platform-technologies/fbx-sdk-2019-0 ](url)

**Comment by NickHardeman** [comment]
Hi Thank you, 
I added the Release and Debug libs for the fbx 2016 version of the libs (Debug is zipped since it was so large). At some point I will upgrade to the 2019 libs when I can test on all platforms.

**Comment by NickHardeman** [comment]
just upgraded the libs to 2019.5, the debug lib for Windows is needs to be unzipped before being used.
